# Generated by Django 5.0.4 on 2024-08-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=200)),
                ('student_prn', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=200)),
                ('student_phone', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254)),
                ('student_address', models.TextField()),
            ],
        ),
    ]
